In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
import re
import joblib
import string

In [2]:
fake = pd.read_csv('Fake.csv')
true = pd.read_csv('True.csv')

In [3]:
fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [4]:
true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [5]:
fake['class'] = 0
true['class'] = 1

In [7]:
data = pd.concat([fake,true],axis=0)

In [8]:
data.sample(10)

,title,text,subject,date,class
8961,Conservatives Invent Conspiracy Theory To Bla...,Even the crankiest section of America s right ...,News,"January 5, 2016",0
4858,"Sarah Palin Faceplants, Immediately Starts Sp...",Half-term Governor of Alaska and professional ...,News,"August 29, 2016",0
10778,"Sanders, Trump give union hope in fight for Ca...",INDIANAPOLIS (Reuters) - Duane Oreskowic was s...,politicsNews,"February 19, 2016",1
8773,President Obama Hammers Republicans: They’re ...,A day after he schooled Republicans during his...,News,"January 13, 2016",0
8696,"Carlos Santana Praises President Obama, Says ...","In an open letter to President Obama, legendar...",News,"January 17, 2016",0
2026,"Trump calls Egypt's Sisi, says keen to overcom...",CAIRO (Reuters) - U.S. President Donald Trump ...,politicsNews,"August 25, 2017",1
20607,"Irma to stress-test Florida insurers, reinsure...",(Reuters) - Florida s insurance and reinsuranc...,worldnews,"September 8, 2017",1
7519,Legendary Investigative Journalist Carl Berns...,Veteran investigative reporter Carl Bernstein ...,News,"March 13, 2016",0
546,JPMorgan's Dimon says Trump likely to be a one...,"CHICAGO/NEW YORK (Reuters) - Jamie Dimon, chie...",politicsNews,"November 22, 2017",1
14827,Lebanon's Hariri shackled by bigger outside fo...,BEIRUT (Reuters) - Nothing so encapsulated th...,worldnews,"November 13, 2017",1